- id: 1
  key: rupee
  code: inr
  symbol: "₹#"
  coin: false
  precision: 2
  assets:
    accounts:
      -
        bank: 'Indian Central Bank'
        address: '6225 0885 6022 3501'
        password: '111111'
        tel: '95555'
- id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  rpc: http://Ken111:asdfghjkl890ASDFGHJKL111@127.0.0.1:18332
  blockchain: https://live.blockcypher.com/btc-testnet/tx/#{txid}
  address_url: https://testnet.blockexplorer.com/address/#{address}
  # blockchain: https://blockchain.info/tx/#{txid}
  # address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3

- id: 3
  key: ether
  code: eth
  symbol: "฿"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://192.169.153.139
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/address/#{address}
  assets:
    accounts:
      -
        address: 0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44
        #address: 0x8d05771a6523fe59fda4517ac348cdd6f6862c49
- id: 4
  key: litecoin
  code: ltc
  symbol: "Ł"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://Ken:asdfghjkl890ASDFGHJKL*()@127.0.0.1:9332
  blockchain: http://ltc.blockr.io/tx/info/#{txid}
  address_url: http://ltc.blockr.io/address/info/#{address}
  assets:
    accounts:
      -
        address: LUJFBiG8DEcjRJdgUgGzENKfwMMkxucyuZ
- id: 5
  key: dashcoin
  code: dash
  symbol: "D"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://Ken:asdfghjkl890ASDFGHJKL*()@127.0.0.1:29080
  blockchain: https://chainradar.com/dsh/transaction/#{txid}
  address_url: https://etherscan.io/address/#{address}
  assets:
    accounts:
      -
        address:  0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44
- id: 6
  key: zcash
  code: zec
  symbol: "Z"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://zcash:zcashpassword12345@127.0.0.1:8232
  blockchain: http://explorer.zcha.in/transactions/#{txid}
  address_url: https://etherscan.io/address/#{address}
  assets:
    accounts:
      -
        address: 0x4bA2474e063Aec44e33F2Bf7Fb9e4e2878dBaB44
- id: 7
  key: ripple
  code: xrp
  symbol: "x"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  # rpc: https://rBuNBaLtsJ2DLY9W6TW8s3woyi5SYNsnEe:shX8zKhVTiBQs1YCoDcUpFUd6jTjS@s.altnet.rippletest.net:51234
  # rpc: https://s1.ripple.com:51234
  rpc: https://127.0.0.1:5005
  blockchain: https://bithomp.com/explorer/#{txid}
  address_url: https://bithomp.com/explorer/#{address}
  assets:
    accounts:
      -
        seed: snoPBrXtMeMyMHUVTgbuqAfg1SuTb
        key_type: secp256k1
- id: 8
  key: peercoin
  code: ppc
  symbol: "p"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://peercoinrpc:peercoinrpcpassword123@127.0.0.1:9902
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/address/#{address}
  assets:
    accounts:
      -
        address: 0x4bA2474e063Aec54e23F2Bf7Fb9e4e2878dBaB44
- id: 9
  key: namecoin
  code: nmc
  symbol: "N"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://namecoinrpc:namecoinrpcpassword123@127.0.0.1:8336
  blockchain: https://namecha.in/tx/#{txid}
  address_url: https://namecha.in/address/#{address}
  assets:
    accounts:
      -
        address: 0x4bA2474e063Aea44e23F2Bf7Fb9e4e2878dBaB44
- id: 10
  key: monero
  code: xmr
  symbol: "M"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://192.169.153.139:18082/json_rpc
  blockchain: https://moneroblocks.info/tx/#{txid}
  address_url: https://moneroblocks.info/block/#{address}
  assets:
    accounts:
      -
        address: 0x4bA2474e063Aea44e23F2Bf7Fb9e4e2878dBaB44
- id: 11
  key: bitcoincash
  code: bch
  symbol: "฿"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://Ken111:asdfghjkl890ASDFGHJKL111@127.0.0.1:8887
  blockchain: https://bitcoincash.blockexplorer.com/tx/#{txid}
  address_url: https://bitcoincash.blockexplorer.com/address/#{address}
  assets:
    accounts:
      -
        address: 0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44
- id: 12
  key: usdt
  code: usdt
  symbol: "$"
  coin: true
  quick_withdraw_max: 0
  rpc: http://usdtrpc:usdtrpcpassword123@127.0.0.1:8332
  blockchain: https://live.blockcypher.com/btc-testnet/tx/#{txid}
  address_url: https://testnet.blockexplorer.com/address/#{address}
  # blockchain: https://blockchain.info/tx/#{txid}
  # address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
# - id: 12
#   key: rep
#   code: rep
#   symbol: "฿"
#   coin: true
#   precision: 4
#   quick_withdraw_max: 0
#   rpc: http://localhost
#   blockchain: https://etherscan.io/tx/#{txid}
#   address_url: https://etherscan.io/address/#{address}
#   assets:
#     accounts:
#       -
#         address: 0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44
# - id: 10
#   key: bcc
#   code: bcc
#   symbol: "฿"
#   coin: true
#   precision: 4
#   quick_withdraw_max: 0
#   rpc: http://localhost
#   blockchain: https://etherscan.io/tx/#{txid}
#   address_url: https://etherscan.io/address/#{address}
#   assets:
#     accounts:
#       -
#         address: 0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44
# - id: 11
#   key: bts
#   code: bts
#   symbol: "฿"
#   coin: true
#   precision: 4
#   quick_withdraw_max: 0
#   rpc: http://localhost
#   blockchain: https://etherscan.io/tx/#{txid}
#   address_url: https://etherscan.io/address/#{address}
#   assets:
#     accounts:
#       -
#         address: 0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44
# - id: 12
#   key: etc
#   code: etc
#   symbol: "E"
#   coin: true
#   precision: 4
#   quick_withdraw_max: 0
#   rpc: http://localhost
#   blockchain: https://etherscan.io/tx/#{txid}
#   address_url: https://etherscan.io/address/#{address}
#   assets:
#     accounts:
#       -
#         address: 0x4bA2474e063Aec44e2F2Bf7Fb9e4e2878dBaB44